name: CI
on:
  push:
    branches: dev
    paths:
      - 'packages/cli/**'
  pull_request:
    branches: dev
    paths:
      - 'packages/cli/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build cli
      - run: yarn test:ci cli
