# This is a basic workflow to help you get started with Actions

name: Docker Prod Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push to prod branch
  push:
    branches: prod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: shrink/actions-docker-registry-tag@v2
        with:
          registry: ghcr.io
          token: ${{ secrets.GHCR_PAT }}
          repository: oasis-sh/oasis
          target: ${{ github.sha }}
          tags: |
            prod

  deploy:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            docker pull ghcr.io/oasis-sh/oasis:prod
            cd /opt/oasis/docker/prod
            docker-compose stop web
            docker-compose rm -f web
            docker-compose up -d
            docker image prune -f
          host: ${{ secrets.SSH_HOST }}
          user: ci-runner
          key: ${{ secrets.SSH_DEPLOY_KEY }}
